apiVersion: v1
kind: Service
metadata:
  name: flux-backend
  labels:
    app: flux-backend
spec:
  ports:
    - port: 8080
      name: flux-backend
  selector:
    app: flux-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-backend
  labels:
    app: flux-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux-backend
  template:
    metadata:
      labels:
        app: flux-backend
    spec:
      containers:
        - name: flux-backend
          image: jwenz723/demohttp-backend:026fbb8-dirty
          args:
            - "-addr=:8080"
          ports:
            - containerPort: 8080
