---
apiVersion: v1
kind: Service
metadata:
  name: demohttp-backend
  labels:
    app: demohttp-backend
spec:
  ports:
  - port: 8080
    name: demohttp-backend
  selector:
    app: demohttp-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demohttp-backend
  labels:
    app: demohttp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demohttp-backend
  template:
    metadata:
      labels:
        app: demohttp-backend
    spec:
      containers:
      - name: demohttp-backend
        image: jwenz723/demohttp-backend:d2742ba-dirty
        args:
        - "-addr=:8080"
        ports:
        - containerPort: 8080
