apiVersion: v1
kind: Service
metadata:
  name: flux-frontend
  labels:
    app: flux-frontend
spec:
  ports:
    - port: 8080
      name: flux-frontend
  selector:
    app: flux-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-frontend
  labels:
    app: flux-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux-frontend
  template:
    metadata:
      labels:
        app: flux-frontend
    spec:
      containers:
        - name: flux-frontend
          image: jwenz723/demohttp-frontend:026fbb8-dirty
          args:
            - "-addr=:8080"
            - "-backend-addr=http://flux-backend:8080"
          ports:
            - containerPort: 8080
