apiVersion: v1
kind: Service
metadata:
  name: demohttp-frontend
  labels:
    app: demohttp-frontend
spec:
  ports:
    - port: 8080
      name: demohttp-frontend
  selector:
    app: demohttp-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demohttp-frontend
  labels:
    app: demohttp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demohttp-frontend
  template:
    metadata:
      labels:
        app: demohttp-frontend
    spec:
      containers:
        - name: demohttp-frontend
          image: jwenz723/demohttp-frontend:026fbb8-dirty
          args:
            - "-addr=:8080"
            - "-backend-addr=http://demohttp-backend:8080"
          ports:
            - containerPort: 8080
